name: github pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "repository"=$REPOSITORY >> $GITHUB_OUTPUT

      - name: Flutter Action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter build
        run: flutter build web --base-href /${{ steps.version.outputs.repository }}/ --release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
